/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Breaks Domain Use Cases
 * 
 * List of all use case names for the breaks domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BREAKS_USE_CASES = [
  "executeAssignBreakCase",
  "executeEscalateBreakCase",
  "executeGetBreakCase",
  "executeListBreakCases",
  "executeOpenBreakCase",
  "executeResolveBreakCase"
] as const;
