/**
 * GetParticipant DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetParticipantParams } from "@settora/core/participants";

export function createGetParticipantRequest(overrides: Partial<GetParticipantParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
