/**
 * ListParticipant DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListParticipantsParams } from "@settora/core/participants";

export function createListParticipantRequest(overrides: Partial<ListParticipantsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
