/**
 * Lock DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Lock DTOs
 *
 * DDD: Application DTOs for Lock use cases.
 */

import type { GetCollateralLockParams, ListCollateralLocksParams } from "@settora/core/collateral/types";

export type ListCollateralLocksInput = ListCollateralLocksParams;

export type GetCollateralLockInput = GetCollateralLockParams;

export type ListCollateralLocksOutput = {};

export type GetCollateralLockOutput = {};
