/**
 * Release DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Release DTOs
 *
 * DDD: Application DTOs for Release use cases.
 */

import type { ReleaseCollateralLockParams, ReleaseCollateralLockRequestInput } from "@settora/core/collateral/types";

export type ReleaseCollateralLockInput = ReleaseCollateralLockParams & ReleaseCollateralLockRequestInput;

export type ReleaseCollateralLockOutput = {};
