/**
 * Repository interface for Participant
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ParticipantEntity
} from "../models/participant.entity.js";
import type {
  ListParticipantsParams,
  Participant,
  UpdateParticipantRequestInput
} from "../types/index.js";
/**
 * ParticipantRepository Interface
 */
export interface ParticipantRepository extends CreateUpdateReadRepository<ParticipantEntity, Participant, UpdateParticipantRequestInput, string, ListParticipantsParams> {

}
