/**
 * GetParticipant handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getParticipant } from "@settora/api-server/domains/participants/handlers";
import type { ParticipantsDDDDependencies } from "@settora/api-server/domains/participants";
import { createParticipant as createParticipantEntity } from "@settora/factories/participants";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@settora/tests/shared";
import { PARTICIPANTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetParticipant", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ParticipantsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ParticipantsDDDDependencies>(
      PARTICIPANTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createParticipantEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetParticipant, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { participantId: entity.id };

    await getParticipant(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetParticipant.execute).toHaveBeenCalledWith(expect.objectContaining({ participantId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { participantId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetParticipant, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getParticipant(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
