/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-participant.handler.test.js";
export * from "./list-participants.handler.test.js";
export * from "./register-participant.handler.test.js";
export * from "./update-participant.handler.test.js";
