/**
 * EscalateBreakCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { escalateBreakCase } from "@settora/api-server/domains/breaks/handlers";
import type { BreaksDDDDependencies } from "@settora/api-server/domains/breaks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@settora/tests/shared";
import { BREAKS_USE_CASES } from "../__factories__/use-cases.js";

describe("EscalateBreakCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BreaksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BreaksDDDDependencies>(
      BREAKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeEscalateBreakCase, "execute").mockResolvedValue(useCaseResult);

    await escalateBreakCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeEscalateBreakCase.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
