/**
 * Routes for Instruction
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSettlementInstruction, getSettlementInstruction, listSettlementInstructions } from "../handlers/instruction.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function instructionRoutes(fastify: FastifyInstance) {
  // POST /v1/settlements/instructions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/settlements/instructions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementsDependenciesForRequest();
        await createSettlementInstruction(request, reply, deps);
      });
    }
  );


  // GET /v1/settlements/instructions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlements/instructions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementsDependenciesForRequest();
        await listSettlementInstructions(request, reply, deps);
      });
    }
  );


  // GET /v1/settlements/instructions/{instructionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlements/instructions/:instructionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { instructionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementsDependenciesForRequest();
        await getSettlementInstruction(request, reply, deps);
      });
    }
  );


}
