/**
 * Handlers for Escalate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BreaksDomainModule } from "../dependencies/breaks-ddd.dependencies.js";
import type { EscalateBreakCaseInput } from "@settora/services/breaks";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/breaks/{breakId}/escalate
 * Operation: escalateBreakCase
 */
export async function escalateBreakCase(
  request: FastifyRequest<{ Params: { breakId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreaksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EscalateBreakCaseInput = {
    breakId: request.params.breakId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.escalates.get.execute(input);
  return reply.code(200).send(result);
}


