/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./assign.handlers.js";
export * from "./break.handlers.js";
export * from "./escalate.handlers.js";
export * from "./resolve.handlers.js";
