/**
 * Routes for Subscription
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSupervisorySubscription, getSupervisorySubscription, listSupervisorySubscriptions } from "../handlers/subscription.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function subscriptionRoutes(fastify: FastifyInstance) {
  // POST /v1/supervision/subscriptions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/supervision/subscriptions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSupervisionDependenciesForRequest();
        await createSupervisorySubscription(request, reply, deps);
      });
    }
  );


  // GET /v1/supervision/subscriptions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/supervision/subscriptions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSupervisionDependenciesForRequest();
        await listSupervisorySubscriptions(request, reply, deps);
      });
    }
  );


  // GET /v1/supervision/subscriptions/{subscriptionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/supervision/subscriptions/:subscriptionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { subscriptionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSupervisionDependenciesForRequest();
        await getSupervisorySubscription(request, reply, deps);
      });
    }
  );


}
