/**
 * FeedRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FeedRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FeedRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FeedRepository,
} from "@settora/services/supervision";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FeedRepositoryDdb } from "./feed-repository.ddb.js";

/**
 * FeedRepositoryAdapter
 *
 * Implements FeedRepository port for infrastructure layer.
 */
export class FeedRepositoryAdapter implements FeedRepository {
  private readonly ddb: FeedRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FeedRepositoryDdb(this.dynamoClient);
  }

  async getSupervisoryFeed(input: Parameters<FeedRepository['getSupervisoryFeed']>[0]): Promise<Awaited<ReturnType<FeedRepository['getSupervisoryFeed']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSupervisoryFeed(input);
  }
}
