/**
 * SubscriptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubscriptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubscriptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SubscriptionRepository,
} from "@settora/services/supervision";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SubscriptionRepositoryDdb } from "./subscription-repository.ddb.js";

/**
 * SubscriptionRepositoryAdapter
 *
 * Implements SubscriptionRepository port for infrastructure layer.
 */
export class SubscriptionRepositoryAdapter implements SubscriptionRepository {
  private readonly ddb: SubscriptionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SubscriptionRepositoryDdb(this.dynamoClient);
  }

  async listSupervisorySubscriptions(input: Parameters<SubscriptionRepository['listSupervisorySubscriptions']>[0]): Promise<Awaited<ReturnType<SubscriptionRepository['listSupervisorySubscriptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSupervisorySubscriptions(input);
  }

  async createSupervisorySubscription(input: Parameters<SubscriptionRepository['createSupervisorySubscription']>[0]): Promise<Awaited<ReturnType<SubscriptionRepository['createSupervisorySubscription']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSupervisorySubscription(input);
  }

  async getSupervisorySubscription(input: Parameters<SubscriptionRepository['getSupervisorySubscription']>[0]): Promise<Awaited<ReturnType<SubscriptionRepository['getSupervisorySubscription']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSupervisorySubscription(input);
  }
}
