/**
 * ParticipantRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ParticipantRepository Port
 *
 * DDD: Application port for participantrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetParticipantInput, GetParticipantOutput, ListParticipantsInput, ListParticipantsOutput, RegisterParticipantInput, RegisterParticipantOutput, UpdateParticipantInput, UpdateParticipantOutput } from "../dto/participant.dto";
export interface ParticipantRepository {
  listParticipants(input: ListParticipantsInput): Promise<ListParticipantsOutput>;
  registerParticipant(input: RegisterParticipantInput): Promise<RegisterParticipantOutput>;
  getParticipant(input: GetParticipantInput): Promise<GetParticipantOutput>;
  updateParticipant(input: UpdateParticipantInput): Promise<UpdateParticipantOutput>;
}

export type { GetParticipantInput, GetParticipantOutput, ListParticipantsInput, ListParticipantsOutput, RegisterParticipantInput, RegisterParticipantOutput, UpdateParticipantInput, UpdateParticipantOutput } from "../dto/participant.dto";
