/**
 * ExecuteListBreakCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBreakCases Use Case
 *
 * DDD: Application use case for list Break.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBreakCasesInput, ListBreakCasesOutput } from "../dto/break.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { BreakRepository } from "../ports";

export class ExecuteListBreakCases {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breakRepo: BreakRepository
  ) {}

  async execute(input: ListBreakCasesInput): Promise<ListBreakCasesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.breaksId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.breakRepo.listBreakCases({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBreakCasesOutput;
  }
}
