/**
 * ExecuteGetBreakCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBreakCase Use Case
 *
 * DDD: Application use case for get Break.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBreakCaseInput, GetBreakCaseOutput } from "../dto/break.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { BreakRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBreakCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breakRepo: BreakRepository
  ) {}

  async execute(input: GetBreakCaseInput): Promise<GetBreakCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.breaksId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).breakId) {
      throw new ValidationError("breakId is required");
    }
    const breakId = (input as any).breakId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.breakRepo.getBreakCase({ breakId: breakId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${breakId}`);
    }

    return entity as GetBreakCaseOutput;
  }
}
