/**
 * CancelSettlementInstruction handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { cancelSettlementInstruction } from "@settora/api-server/domains/settlements/handlers";
import type { SettlementsDDDDependencies } from "@settora/api-server/domains/settlements";
import { createUpdateCancelRequest } from "@settora/factories/settlements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@settora/tests/shared";
import { SETTLEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CancelSettlementInstruction", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SettlementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SettlementsDDDDependencies>(
      SETTLEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateCancelRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { instructionId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCancelSettlementInstruction, "execute").mockResolvedValue(useCaseResult);

    await cancelSettlementInstruction(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCancelSettlementInstruction.execute).toHaveBeenCalledWith(expect.objectContaining({ instructionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
