/**
 * AssertionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssertionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AssertionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AssertionRepository,
} from "@settora/services/deals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AssertionRepositoryDdb } from "./assertion-repository.ddb.js";

/**
 * AssertionRepositoryAdapter
 *
 * Implements AssertionRepository port for infrastructure layer.
 */
export class AssertionRepositoryAdapter implements AssertionRepository {
  private readonly ddb: AssertionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AssertionRepositoryDdb(this.dynamoClient);
  }

  async listDealAssertions(input: Parameters<AssertionRepository['listDealAssertions']>[0]): Promise<Awaited<ReturnType<AssertionRepository['listDealAssertions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDealAssertions(input);
  }

  async submitStateAssertion(input: Parameters<AssertionRepository['submitStateAssertion']>[0]): Promise<Awaited<ReturnType<AssertionRepository['submitStateAssertion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitStateAssertion(input);
  }
}
