/**
 * CorporateActionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorporateActionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CorporateActionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CorporateActionRepository,
} from "@settora/services/deals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CorporateActionRepositoryDdb } from "./corporate-action-repository.ddb.js";

/**
 * CorporateActionRepositoryAdapter
 *
 * Implements CorporateActionRepository port for infrastructure layer.
 */
export class CorporateActionRepositoryAdapter implements CorporateActionRepository {
  private readonly ddb: CorporateActionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CorporateActionRepositoryDdb(this.dynamoClient);
  }

  async listCorporateActionEvents(input: Parameters<CorporateActionRepository['listCorporateActionEvents']>[0]): Promise<Awaited<ReturnType<CorporateActionRepository['listCorporateActionEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCorporateActionEvents(input);
  }

  async recordCorporateActionEvent(input: Parameters<CorporateActionRepository['recordCorporateActionEvent']>[0]): Promise<Awaited<ReturnType<CorporateActionRepository['recordCorporateActionEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordCorporateActionEvent(input);
  }
}
