/**
 * DealRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DealRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DealRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DealRepository,
} from "@settora/services/deals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DealRepositoryDdb } from "./deal-repository.ddb.js";

/**
 * DealRepositoryAdapter
 *
 * Implements DealRepository port for infrastructure layer.
 */
export class DealRepositoryAdapter implements DealRepository {
  private readonly ddb: DealRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DealRepositoryDdb(this.dynamoClient);
  }

  async listTradeDeals(input: Parameters<DealRepository['listTradeDeals']>[0]): Promise<Awaited<ReturnType<DealRepository['listTradeDeals']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTradeDeals(input);
  }

  async createTradeDeal(input: Parameters<DealRepository['createTradeDeal']>[0]): Promise<Awaited<ReturnType<DealRepository['createTradeDeal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createTradeDeal(input);
  }

  async getTradeDeal(input: Parameters<DealRepository['getTradeDeal']>[0]): Promise<Awaited<ReturnType<DealRepository['getTradeDeal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTradeDeal(input);
  }
}
