/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./agreed-state-repository.ddb.js";
export * from "./assertion-repository.ddb.js";
export * from "./corporate-action-repository.ddb.js";
export * from "./deal-repository.ddb.js";
export * from "./freeze-field-repository.ddb.js";
export * from "./milestone-repository.ddb.js";
export * from "./provenance-repository.ddb.js";
export * from "./agreed-state-repository.adapter.js";
export * from "./assertion-repository.adapter.js";
export * from "./corporate-action-repository.adapter.js";
export * from "./deal-repository.adapter.js";
export * from "./freeze-field-repository.adapter.js";
export * from "./milestone-repository.adapter.js";
export * from "./provenance-repository.adapter.js";
