/**
 * MilestoneRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MilestoneRepositoryDdb
 *
 * DDD: Infrastructure adapter for Milestone repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { MilestoneRepository } from "@settora/services/deals";

export class MilestoneRepositoryDdb implements MilestoneRepository {
  constructor(private readonly dynamoClient: any) {}

  async listDocumentMilestones(input: Parameters<MilestoneRepository['listDocumentMilestones']>[0]): Promise<Awaited<ReturnType<MilestoneRepository['listDocumentMilestones']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async attestDocumentMilestone(input: Parameters<MilestoneRepository['attestDocumentMilestone']>[0]): Promise<Awaited<ReturnType<MilestoneRepository['attestDocumentMilestone']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
