/**
 * Handlers for Subscription
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SupervisionDomainModule } from "../dependencies/supervision-ddd.dependencies.js";
import type { CreateSupervisorySubscriptionInput, GetSupervisorySubscriptionInput, ListSupervisorySubscriptionsInput } from "@settora/services/supervision";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/supervision/subscriptions
 * Operation: listSupervisorySubscriptions
 */
export async function listSupervisorySubscriptions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SupervisionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSupervisorySubscriptionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.subscriptions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/supervision/subscriptions
 * Operation: createSupervisorySubscription
 */
export async function createSupervisorySubscription(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SupervisionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateSupervisorySubscriptionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.subscriptions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/supervision/subscriptions/{subscriptionId}
 * Operation: getSupervisorySubscription
 */
export async function getSupervisorySubscription(
  request: FastifyRequest<{ Params: { subscriptionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SupervisionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSupervisorySubscriptionInput = {
    subscriptionId: request.params.subscriptionId,
  };
  const result = await deps.useCases.subscriptions.get.execute(input);
  return reply.code(200).send(result);
}


