/**
 * Settlements DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Settlements Domain Module - Composition root
 *
 * DDD: Composition root for settlements domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CancelRepositoryAdapter,
  InstructionRepositoryAdapter,
  SendRepositoryAdapter,
} from "@settora/adapters/settlements";
import { getIdGeneratorService } from "@settora/adapters";
import type { AdapterDynamoDBClient } from "@settora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateSettlementInstruction,
  ExecuteGetSettlementInstruction,
  ExecuteListSettlementInstructions,
} from "@settora/services/settlements/usecases";
// Ports (interfaces)
import type {
  CancelRepository,
  InstructionRepository,
  SendRepository,
} from "@settora/services/settlements/ports";

export interface SettlementsDomainModule {
  repos: {
    cancels: CancelRepository;
    instructions: InstructionRepository;
    sends: SendRepository;
  };
  useCases: {
    instructions: {
      create: ExecuteCreateSettlementInstruction;
      get: ExecuteGetSettlementInstruction;
      list: ExecuteListSettlementInstructions;
    };
  };
}

export function buildSettlementsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SettlementsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      cancels?: CancelRepository;
      instructions?: InstructionRepository;
      sends?: SendRepository;
    } = {};

    obj.cancels = new CancelRepositoryAdapter(dynamoClient);
    obj.instructions = new InstructionRepositoryAdapter(dynamoClient);
    obj.sends = new SendRepositoryAdapter(dynamoClient);
    return {
      cancels: obj.cancels!,
      instructions: obj.instructions!,
      sends: obj.sends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    instructions: {
      create: new ExecuteCreateSettlementInstruction(executionContext, idGenerator, repos.instructions),
      get: new ExecuteGetSettlementInstruction(executionContext, idGenerator, repos.instructions),
      list: new ExecuteListSettlementInstructions(executionContext, idGenerator, repos.instructions),
    },
  };
  return { repos, useCases: useCases as SettlementsDomainModule["useCases"] };
}
