/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Settlements Domain Use Cases
 * 
 * List of all use case names for the settlements domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SETTLEMENTS_USE_CASES = [
  "executeCancelSettlementInstruction",
  "executeCreateSettlementInstruction",
  "executeGetSettlementInstruction",
  "executeListSettlementInstructions",
  "executeSendSettlementInstruction"
] as const;
