/**
 * ListTradeDeals handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listTradeDeals } from "@settora/api-server/domains/deals/handlers";
import type { DealsDDDDependencies } from "@settora/api-server/domains/deals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@settora/tests/shared";
import { DEALS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListTradeDeals", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DealsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DealsDDDDependencies>(
      DEALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListTradeDeals, "execute").mockResolvedValue(useCaseResult);

    await listTradeDeals(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListTradeDeals.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
