/**
 * Collateral DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Collateral Domain Module - Composition root
 *
 * DDD: Composition root for collateral domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  LockRepositoryAdapter,
  ReleaseRepositoryAdapter,
} from "@settora/adapters/collateral";
import { getIdGeneratorService } from "@settora/adapters";
import type { AdapterDynamoDBClient } from "@settora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetCollateralLock,
  ExecuteListCollateralLocks,
} from "@settora/services/collateral/usecases";
// Ports (interfaces)
import type {
  LockRepository,
  ReleaseRepository,
} from "@settora/services/collateral/ports";

export interface CollateralDomainModule {
  repos: {
    locks: LockRepository;
    releases: ReleaseRepository;
  };
  useCases: {
    locks: {
      get: ExecuteGetCollateralLock;
      list: ExecuteListCollateralLocks;
    };
  };
}

export function buildCollateralDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CollateralDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      locks?: LockRepository;
      releases?: ReleaseRepository;
    } = {};

    obj.locks = new LockRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    return {
      locks: obj.locks!,
      releases: obj.releases!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    locks: {
      get: new ExecuteGetCollateralLock(executionContext, idGenerator, repos.locks),
      list: new ExecuteListCollateralLocks(executionContext, idGenerator, repos.locks),
    },
  };
  return { repos, useCases: useCases as CollateralDomainModule["useCases"] };
}
