/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@settora/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "breaks", "collateral", "deals", "finality", "governance", "identity", "participants", "settlements", "supervision"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      breaks: [{ method: "GET", path: "/v1/breaks" }, { method: "POST", path: "/v1/breaks" }, { method: "GET", path: "/v1/breaks/:breakId" }, { method: "POST", path: "/v1/breaks/:breakId/assign" }, { method: "POST", path: "/v1/breaks/:breakId/resolve" }, { method: "POST", path: "/v1/breaks/:breakId/escalate" }],
      collateral: [{ method: "GET", path: "/v1/collateral/locks" }, { method: "GET", path: "/v1/collateral/locks/:lockId" }, { method: "POST", path: "/v1/collateral/locks/:lockId/release" }],
      deals: [{ method: "GET", path: "/v1/deals" }, { method: "POST", path: "/v1/deals" }, { method: "GET", path: "/v1/deals/:dealId" }, { method: "GET", path: "/v1/deals/:dealId/assertions" }, { method: "POST", path: "/v1/deals/:dealId/assertions" }, { method: "GET", path: "/v1/deals/:dealId/agreed-state" }, { method: "POST", path: "/v1/deals/:dealId/freeze-fields" }, { method: "GET", path: "/v1/deals/:dealId/milestones" }, { method: "POST", path: "/v1/deals/:dealId/milestones" }, { method: "GET", path: "/v1/deals/:dealId/corporate-actions" }, { method: "POST", path: "/v1/deals/:dealId/corporate-actions" }, { method: "GET", path: "/v1/provenance/:assetId" }],
      finality: [{ method: "GET", path: "/v1/finality/attestations" }, { method: "POST", path: "/v1/finality/attestations" }, { method: "GET", path: "/v1/finality/attestations/:attestationId" }],
      governance: [{ method: "GET", path: "/v1/governance/rulebooks" }, { method: "POST", path: "/v1/governance/rulebooks" }, { method: "GET", path: "/v1/governance/rulebooks/:rulebookId" }, { method: "GET", path: "/v1/governance/votes" }, { method: "POST", path: "/v1/governance/votes" }, { method: "POST", path: "/v1/participants/:participantId/suspend" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      participants: [{ method: "GET", path: "/v1/participants" }, { method: "POST", path: "/v1/participants" }, { method: "GET", path: "/v1/participants/:participantId" }, { method: "PATCH", path: "/v1/participants/:participantId" }],
      settlements: [{ method: "GET", path: "/v1/settlements/instructions" }, { method: "POST", path: "/v1/settlements/instructions" }, { method: "GET", path: "/v1/settlements/instructions/:instructionId" }, { method: "POST", path: "/v1/settlements/instructions/:instructionId/send" }, { method: "POST", path: "/v1/settlements/instructions/:instructionId/cancel" }],
      supervision: [{ method: "GET", path: "/v1/supervision/subscriptions" }, { method: "POST", path: "/v1/supervision/subscriptions" }, { method: "GET", path: "/v1/supervision/subscriptions/:subscriptionId" }, { method: "GET", path: "/v1/supervision/subscriptions/:subscriptionId/feed" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
