/**
 * GetProvenance DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAssetProvenanceParams } from "@settora/core/deals";

export function createGetProvenanceRequest(overrides: Partial<GetAssetProvenanceParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
