/**
 * Participant DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Participant DTOs
 *
 * DDD: Application DTOs for Participant use cases.
 */

import type { GetParticipantParams, ListParticipantsParams, RegisterParticipantRequestInput, UpdateParticipantParams, UpdateParticipantRequestInput } from "@settora/core/participants/types";

export type ListParticipantsInput = ListParticipantsParams;

export type RegisterParticipantInput = RegisterParticipantRequestInput;

export type GetParticipantInput = GetParticipantParams;

export type UpdateParticipantInput = UpdateParticipantParams & UpdateParticipantRequestInput;

export type ListParticipantsOutput = {};

export type RegisterParticipantOutput = {};

export type GetParticipantOutput = {};

export type UpdateParticipantOutput = {};
