/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  RulebookRepositoryAdapter,
  SuspendRepositoryAdapter,
  VoteRepositoryAdapter,
} from "@settora/adapters/governance";
import { getIdGeneratorService } from "@settora/adapters";
import type { AdapterDynamoDBClient } from "@settora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCastGovernanceVote,
  ExecuteGetRulebookVersion,
  ExecuteListGovernanceVotes,
  ExecuteListRulebookVersions,
  ExecutePublishRulebookVersion,
} from "@settora/services/governance/usecases";
// Ports (interfaces)
import type {
  RulebookRepository,
  SuspendRepository,
  VoteRepository,
} from "@settora/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    rulebooks: RulebookRepository;
    suspends: SuspendRepository;
    votes: VoteRepository;
  };
  useCases: {
    rulebooks: {
      get: ExecuteGetRulebookVersion;
      list: ExecuteListRulebookVersions;
    };
    votes: {
      get: ExecuteCastGovernanceVote;
      list: ExecuteListGovernanceVotes;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      rulebooks?: RulebookRepository;
      suspends?: SuspendRepository;
      votes?: VoteRepository;
    } = {};

    obj.rulebooks = new RulebookRepositoryAdapter(dynamoClient);
    obj.suspends = new SuspendRepositoryAdapter(dynamoClient);
    obj.votes = new VoteRepositoryAdapter(dynamoClient);
    return {
      rulebooks: obj.rulebooks!,
      suspends: obj.suspends!,
      votes: obj.votes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    rulebooks: {
      get: new ExecuteGetRulebookVersion(executionContext, idGenerator, repos.rulebooks),
      list: new ExecuteListRulebookVersions(executionContext, idGenerator, repos.rulebooks),
    },
    votes: {
      get: new ExecuteCastGovernanceVote(executionContext, idGenerator, repos.votes),
      list: new ExecuteListGovernanceVotes(executionContext, idGenerator, repos.votes),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
