/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @settora/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@settora/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@settora/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@settora/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@settora/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@settora/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _breaks from "./breaks/index.js";
import * as _collateral from "./collateral/index.js";
import * as _deals from "./deals/index.js";
import * as _finality from "./finality/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _participants from "./participants/index.js";
import * as _settlements from "./settlements/index.js";
import * as _supervision from "./supervision/index.js";

// Export as namespaces
export const _shared = __shared;
export const breaks = _breaks;
export const collateral = _collateral;
export const deals = _deals;
export const finality = _finality;
export const governance = _governance;
export const identity = _identity;
export const participants = _participants;
export const settlements = _settlements;
export const supervision = _supervision;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@settora/core"; activity.types.*
//   - Direct exports: import * from "@settora/core/activity/types/index.js"
//   - Direct exports: import * from "@settora/core/activity/repositories/index.js"
//   - Direct exports: import * from "@settora/core/activity/models/index.js"
//   - Direct exports: import * from "@settora/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Breaks Service
export { schemas as BreaksSchemas } from "./breaks/schemas/breaks.schemas.js";

// Collateral Service
export { schemas as CollateralSchemas } from "./collateral/schemas/collateral.schemas.js";

// Deals Service
export { schemas as DealsSchemas } from "./deals/schemas/deals.schemas.js";

// Finality Service
export { schemas as FinalitySchemas } from "./finality/schemas/finality.schemas.js";

// Governance Service
export { schemas as GovernanceSchemas } from "./governance/schemas/governance.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Participants Service
export { schemas as ParticipantsSchemas } from "./participants/schemas/participants.schemas.js";

// Settlements Service
export { schemas as SettlementsSchemas } from "./settlements/schemas/settlements.schemas.js";

// Supervision Service
export { schemas as SupervisionSchemas } from "./supervision/schemas/supervision.schemas.js";

