/**
 * ExecutePublishRulebookVersion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishRulebookVersion Use Case
 *
 * DDD: Application use case for get Rulebook.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishRulebookVersionInput, PublishRulebookVersionOutput } from "../dto/rulebook.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { RulebookPublisher, RulebookRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecutePublishRulebookVersion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rulebookRepository: RulebookRepository,
    private readonly rulebookPublisher: RulebookPublisher
  ) {}

  async execute(input: PublishRulebookVersionInput): Promise<PublishRulebookVersionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.governanceId();

    // All field names extracted from OpenAPI spec: effectiveFrom, schemaDiff, summary, version
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.rulebookPublisher.publishRulebookVersion({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as PublishRulebookVersionOutput;
  }
}
