/**
 * ExecuteGetRulebookVersion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRulebookVersion Use Case
 *
 * DDD: Application use case for get Rulebook.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRulebookVersionInput, GetRulebookVersionOutput } from "../dto/rulebook.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { RulebookRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetRulebookVersion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rulebook: RulebookRepository
  ) {}

  async execute(input: GetRulebookVersionInput): Promise<GetRulebookVersionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.governanceId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).rulebookId) {
      throw new ValidationError("rulebookId is required");
    }
    const rulebookId = (input as any).rulebookId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rulebook.getRulebookVersion({ rulebookId: rulebookId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${rulebookId}`);
    }

    return entity as GetRulebookVersionOutput;
  }
}
