/**
 * ExecuteUpdateParticipant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateParticipant Use Case
 *
 * DDD: Application use case for update Participant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateParticipantInput, UpdateParticipantOutput } from "../dto/participant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { ParticipantRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateParticipant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly participant: ParticipantRepository
  ) {}

  async execute(input: UpdateParticipantInput): Promise<UpdateParticipantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.participantsId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).participantId) {
      throw new ValidationError("participantId is required");
    }
    const participantId = (input as any).participantId;

    // Load existing entity
    const existing = await this.participant.getParticipant({ participantId: participantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${participantId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.participant.updateParticipant({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateParticipantOutput;
  }
}
