/**
 * Routes for Break
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getBreakCase, listBreakCases, openBreakCase } from "../handlers/break.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function breakRoutes(fastify: FastifyInstance) {
  // GET /v1/breaks (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/breaks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBreaksDependenciesForRequest();
        await listBreakCases(request, reply, deps);
      });
    }
  );


  // POST /v1/breaks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/breaks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBreaksDependenciesForRequest();
        await openBreakCase(request, reply, deps);
      });
    }
  );


  // GET /v1/breaks/{breakId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/breaks/:breakId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { breakId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBreaksDependenciesForRequest();
        await getBreakCase(request, reply, deps);
      });
    }
  );


}
