/**
 * Routes for Escalate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { escalateBreakCase } from "../handlers/escalate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function escalateRoutes(fastify: FastifyInstance) {
  // POST /v1/breaks/{breakId}/escalate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/breaks/:breakId/escalate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { breakId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBreaksDependenciesForRequest();
        await escalateBreakCase(request, reply, deps);
      });
    }
  );


}
