/**
 * LockRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LockRepository Port
 *
 * DDD: Application port for lockrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCollateralLockInput, GetCollateralLockOutput, ListCollateralLocksInput, ListCollateralLocksOutput } from "../dto/lock.dto";
export interface LockRepository {
  listCollateralLocks(input: ListCollateralLocksInput): Promise<ListCollateralLocksOutput>;
  getCollateralLock(input: GetCollateralLockInput): Promise<GetCollateralLockOutput>;
}

export type { GetCollateralLockInput, GetCollateralLockOutput, ListCollateralLocksInput, ListCollateralLocksOutput } from "../dto/lock.dto";
