/**
 * Assign DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assign DTOs
 *
 * DDD: Application DTOs for Assign use cases.
 */

import type { AssignBreakCaseParams, AssignBreakCaseRequestInput } from "@settora/core/breaks/types";

export type AssignBreakCaseInput = AssignBreakCaseParams & AssignBreakCaseRequestInput;

export type AssignBreakCaseOutput = {};
