/**
 * Escalate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Escalate DTOs
 *
 * DDD: Application DTOs for Escalate use cases.
 */

import type { EscalateBreakCaseParams, EscalateBreakCaseRequestInput } from "@settora/core/breaks/types";

export type EscalateBreakCaseInput = EscalateBreakCaseParams & EscalateBreakCaseRequestInput;

export type EscalateBreakCaseOutput = {};
