/**
 * Handlers for Lock
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CollateralDomainModule } from "../dependencies/collateral-ddd.dependencies.js";
import type { GetCollateralLockInput, ListCollateralLocksInput } from "@settora/services/collateral";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/collateral/locks
 * Operation: listCollateralLocks
 */
export async function listCollateralLocks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], dealId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CollateralDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCollateralLocksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.locks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/collateral/locks/{lockId}
 * Operation: getCollateralLock
 */
export async function getCollateralLock(
  request: FastifyRequest<{ Params: { lockId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CollateralDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCollateralLockInput = {
    lockId: request.params.lockId,
  };
  const result = await deps.useCases.locks.get.execute(input);
  return reply.code(200).send(result);
}


