/**
 * Handlers for Release
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CollateralDomainModule } from "../dependencies/collateral-ddd.dependencies.js";
import type { ReleaseCollateralLockInput } from "@settora/services/collateral";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/collateral/locks/{lockId}/release
 * Operation: releaseCollateralLock
 */
export async function releaseCollateralLock(
  request: FastifyRequest<{ Params: { lockId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CollateralDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReleaseCollateralLockInput = {
    lockId: request.params.lockId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.releases.get.execute(input);
  return reply.code(200).send(result);
}


