/**
 * Routes for Attestation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: finality
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getFinalityAttestation, listFinalityAttestations, recordFinalityAttestation } from "../handlers/attestation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function attestationRoutes(fastify: FastifyInstance) {
  // GET /v1/finality/attestations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/finality/attestations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFinalityDependenciesForRequest();
        await listFinalityAttestations(request, reply, deps);
      });
    }
  );


  // POST /v1/finality/attestations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/finality/attestations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFinalityDependenciesForRequest();
        await recordFinalityAttestation(request, reply, deps);
      });
    }
  );


  // GET /v1/finality/attestations/{attestationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/finality/attestations/:attestationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFinalityDependenciesForRequest();
        await getFinalityAttestation(request, reply, deps);
      });
    }
  );


}
