/**
 * CreateSend DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SendSettlementInstructionParams } from "@settora/core/settlements";

export function createCreateSendRequest(overrides: Partial<SendSettlementInstructionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
