/**
 * AssignRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssignRepository Port
 *
 * DDD: Application port for assignrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssignBreakCaseInput, AssignBreakCaseOutput } from "../dto/assign.dto";
export interface AssignRepository {
  assignBreakCase(input: AssignBreakCaseInput): Promise<AssignBreakCaseOutput>;
}

export type { AssignBreakCaseInput, AssignBreakCaseOutput } from "../dto/assign.dto";
