/**
 * BreakRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BreakRepository Port
 *
 * DDD: Application port for breakrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetBreakCaseInput, GetBreakCaseOutput, ListBreakCasesInput, ListBreakCasesOutput, OpenBreakCaseInput, OpenBreakCaseOutput } from "../dto/break.dto";
export interface BreakRepository {
  listBreakCases(input: ListBreakCasesInput): Promise<ListBreakCasesOutput>;
  openBreakCase(input: OpenBreakCaseInput): Promise<OpenBreakCaseOutput>;
  getBreakCase(input: GetBreakCaseInput): Promise<GetBreakCaseOutput>;
}

export type { GetBreakCaseInput, GetBreakCaseOutput, ListBreakCasesInput, ListBreakCasesOutput, OpenBreakCaseInput, OpenBreakCaseOutput } from "../dto/break.dto";
