/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: collateral
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Collateral Domain Use Cases
 * 
 * List of all use case names for the collateral domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COLLATERAL_USE_CASES = [
  "executeGetCollateralLock",
  "executeListCollateralLocks",
  "executeReleaseCollateralLock"
] as const;
