/**
 * GetFinalityAttestation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: finality
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFinalityAttestation } from "@settora/api-server/domains/finality/handlers";
import type { FinalityDDDDependencies } from "@settora/api-server/domains/finality";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@settora/tests/shared";
import { FINALITY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFinalityAttestation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FinalityDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FinalityDDDDependencies>(
      FINALITY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFinalityAttestation, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { attestationId: entity.id };

    await getFinalityAttestation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFinalityAttestation.execute).toHaveBeenCalledWith(expect.objectContaining({ attestationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { attestationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFinalityAttestation, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFinalityAttestation(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
