/**
 * CancelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CancelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CancelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CancelRepository,
} from "@settora/services/settlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CancelRepositoryDdb } from "./cancel-repository.ddb.js";

/**
 * CancelRepositoryAdapter
 *
 * Implements CancelRepository port for infrastructure layer.
 */
export class CancelRepositoryAdapter implements CancelRepository {
  private readonly ddb: CancelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CancelRepositoryDdb(this.dynamoClient);
  }

  async cancelSettlementInstruction(input: Parameters<CancelRepository['cancelSettlementInstruction']>[0]): Promise<Awaited<ReturnType<CancelRepository['cancelSettlementInstruction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.cancelSettlementInstruction(input);
  }
}
