/**
 * InstructionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InstructionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InstructionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InstructionRepository,
} from "@settora/services/settlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InstructionRepositoryDdb } from "./instruction-repository.ddb.js";

/**
 * InstructionRepositoryAdapter
 *
 * Implements InstructionRepository port for infrastructure layer.
 */
export class InstructionRepositoryAdapter implements InstructionRepository {
  private readonly ddb: InstructionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InstructionRepositoryDdb(this.dynamoClient);
  }

  async listSettlementInstructions(input: Parameters<InstructionRepository['listSettlementInstructions']>[0]): Promise<Awaited<ReturnType<InstructionRepository['listSettlementInstructions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSettlementInstructions(input);
  }

  async createSettlementInstruction(input: Parameters<InstructionRepository['createSettlementInstruction']>[0]): Promise<Awaited<ReturnType<InstructionRepository['createSettlementInstruction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSettlementInstruction(input);
  }

  async getSettlementInstruction(input: Parameters<InstructionRepository['getSettlementInstruction']>[0]): Promise<Awaited<ReturnType<InstructionRepository['getSettlementInstruction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSettlementInstruction(input);
  }
}
