/**
 * SendRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SendRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SendRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SendRepository,
} from "@settora/services/settlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SendRepositoryDdb } from "./send-repository.ddb.js";

/**
 * SendRepositoryAdapter
 *
 * Implements SendRepository port for infrastructure layer.
 */
export class SendRepositoryAdapter implements SendRepository {
  private readonly ddb: SendRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SendRepositoryDdb(this.dynamoClient);
  }

  async sendSettlementInstruction(input: Parameters<SendRepository['sendSettlementInstruction']>[0]): Promise<Awaited<ReturnType<SendRepository['sendSettlementInstruction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.sendSettlementInstruction(input);
  }
}
