/**
 * Handlers for Milestone
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DealsDomainModule } from "../dependencies/deals-ddd.dependencies.js";
import type { AttestDocumentMilestoneInput, ListDocumentMilestonesInput } from "@settora/services/deals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/deals/{dealId}/milestones
 * Operation: listDocumentMilestones
 */
export async function listDocumentMilestones(
  request: FastifyRequest<{ Params: { dealId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDocumentMilestonesInput = {
    dealId: request.params.dealId,
  };
  const result = await deps.useCases.milestones.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/deals/{dealId}/milestones
 * Operation: attestDocumentMilestone
 */
export async function attestDocumentMilestone(
  request: FastifyRequest<{ Params: { dealId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AttestDocumentMilestoneInput = {
    dealId: request.params.dealId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.milestones.get.execute(input);
  return reply.code(201).send(result);
}


