/**
 * Handlers for Provenance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DealsDomainModule } from "../dependencies/deals-ddd.dependencies.js";
import type { GetAssetProvenanceInput } from "@settora/services/deals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/provenance/{assetId}
 * Operation: getAssetProvenance
 */
export async function getAssetProvenance(
  request: FastifyRequest<{ Params: { assetId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DealsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAssetProvenanceInput = {
    assetId: request.params.assetId,
  };
  const result = await deps.useCases.provenances.get.execute(input);
  return reply.code(200).send(result);
}


