/**
 * EscalateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EscalateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EscalateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EscalateRepository,
} from "@settora/services/breaks";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EscalateRepositoryDdb } from "./escalate-repository.ddb.js";

/**
 * EscalateRepositoryAdapter
 *
 * Implements EscalateRepository port for infrastructure layer.
 */
export class EscalateRepositoryAdapter implements EscalateRepository {
  private readonly ddb: EscalateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EscalateRepositoryDdb(this.dynamoClient);
  }

  async escalateBreakCase(input: Parameters<EscalateRepository['escalateBreakCase']>[0]): Promise<Awaited<ReturnType<EscalateRepository['escalateBreakCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.escalateBreakCase(input);
  }
}
