/**
 * CorporateAction DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorporateAction DTOs
 *
 * DDD: Application DTOs for CorporateAction use cases.
 */

import type { ListCorporateActionEventsParams, RecordCorporateActionEventParams, RecordCorporateActionEventRequestInput } from "@settora/core/deals/types";

export type ListCorporateActionEventsInput = ListCorporateActionEventsParams;

export type RecordCorporateActionEventInput = RecordCorporateActionEventParams & RecordCorporateActionEventRequestInput;

export type ListCorporateActionEventsOutput = {};

export type RecordCorporateActionEventOutput = {};
