/**
 * Deal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deal DTOs
 *
 * DDD: Application DTOs for Deal use cases.
 */

import type { CreateTradeDealRequestInput, GetTradeDealParams, ListTradeDealsParams } from "@settora/core/deals/types";

export type ListTradeDealsInput = ListTradeDealsParams;

export type CreateTradeDealInput = CreateTradeDealRequestInput;

export type GetTradeDealInput = GetTradeDealParams;

export type ListTradeDealsOutput = {};

export type CreateTradeDealOutput = {};

export type GetTradeDealOutput = {};
