/**
 * Provenance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Provenance DTOs
 *
 * DDD: Application DTOs for Provenance use cases.
 */

import type { GetAssetProvenanceParams } from "@settora/core/deals/types";

export type GetAssetProvenanceInput = GetAssetProvenanceParams;

export type GetAssetProvenanceOutput = {};
