/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@settora/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@settora/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@settora/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _breaks from "./breaks/index.js";
import * as _collateral from "./collateral/index.js";
import * as _deals from "./deals/index.js";
import * as _finality from "./finality/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _participants from "./participants/index.js";
import * as _settlements from "./settlements/index.js";
import * as _supervision from "./supervision/index.js";

// Export as namespaces
export const breaks = _breaks;
export const collateral = _collateral;
export const deals = _deals;
export const finality = _finality;
export const governance = _governance;
export const identity = _identity;
export const participants = _participants;
export const settlements = _settlements;
export const supervision = _supervision;
