/**
 * Handlers for Rulebook
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { GetRulebookVersionInput, ListRulebookVersionsInput, PublishRulebookVersionInput } from "@settora/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/governance/rulebooks
 * Operation: listRulebookVersions
 */
export async function listRulebookVersions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRulebookVersionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.rulebooks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/governance/rulebooks
 * Operation: publishRulebookVersion
 */
export async function publishRulebookVersion(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishRulebookVersionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rulebooks.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/governance/rulebooks/{rulebookId}
 * Operation: getRulebookVersion
 */
export async function getRulebookVersion(
  request: FastifyRequest<{ Params: { rulebookId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRulebookVersionInput = {
    rulebookId: request.params.rulebookId,
  };
  const result = await deps.useCases.rulebooks.get.execute(input);
  return reply.code(200).send(result);
}


