/**
 * Handlers for Vote
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { CastGovernanceVoteInput, ListGovernanceVotesInput } from "@settora/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/governance/votes
 * Operation: listGovernanceVotes
 */
export async function listGovernanceVotes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListGovernanceVotesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.votes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/governance/votes
 * Operation: castGovernanceVote
 */
export async function castGovernanceVote(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CastGovernanceVoteInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.votes.get.execute(input);
  return reply.code(201).send(result);
}


