/**
 * Routes for Suspend
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { suspendParticipant } from "../handlers/suspend.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function suspendRoutes(fastify: FastifyInstance) {
  // POST /v1/participants/{participantId}/suspend (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/participants/:participantId/suspend",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { participantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await suspendParticipant(request, reply, deps);
      });
    }
  );


}
