/**
 * CreateSettlementInstruction handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createSettlementInstruction } from "@settora/api-server/domains/settlements/handlers";
import type { SettlementsDDDDependencies } from "@settora/api-server/domains/settlements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@settora/tests/shared";
import { SETTLEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateSettlementInstruction", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SettlementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SettlementsDDDDependencies>(
      SETTLEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateSettlementInstruction, "execute").mockResolvedValue(useCaseResult);

    await createSettlementInstruction(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateSettlementInstruction.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
