/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-settlement-instruction.handler.test.js";
export * from "./get-settlement-instruction.handler.test.js";
export * from "./list-settlement-instructions.handler.test.js";
