/**
 * CorporateActionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorporateActionRepository Port
 *
 * DDD: Application port for corporateactionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListCorporateActionEventsInput, ListCorporateActionEventsOutput, RecordCorporateActionEventInput, RecordCorporateActionEventOutput } from "../dto/corporate-action.dto";
export interface CorporateActionRepository {
  listCorporateActionEvents(input: ListCorporateActionEventsInput): Promise<ListCorporateActionEventsOutput>;
  recordCorporateActionEvent(input: RecordCorporateActionEventInput): Promise<RecordCorporateActionEventOutput>;
}

export type { ListCorporateActionEventsInput, ListCorporateActionEventsOutput, RecordCorporateActionEventInput, RecordCorporateActionEventOutput } from "../dto/corporate-action.dto";
