/**
 * DealRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DealRepository Port
 *
 * DDD: Application port for dealrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTradeDealInput, CreateTradeDealOutput, GetTradeDealInput, GetTradeDealOutput, ListTradeDealsInput, ListTradeDealsOutput } from "../dto/deal.dto";
export interface DealRepository {
  listTradeDeals(input: ListTradeDealsInput): Promise<ListTradeDealsOutput>;
  createTradeDeal(input: CreateTradeDealInput): Promise<CreateTradeDealOutput>;
  getTradeDeal(input: GetTradeDealInput): Promise<GetTradeDealOutput>;
}

export type { CreateTradeDealInput, CreateTradeDealOutput, GetTradeDealInput, GetTradeDealOutput, ListTradeDealsInput, ListTradeDealsOutput } from "../dto/deal.dto";
