/**
 * FreezeFieldRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FreezeFieldRepository Port
 *
 * DDD: Application port for freezefieldrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { FreezeDealFieldsInput, FreezeDealFieldsOutput } from "../dto/freeze-field.dto";
export interface FreezeFieldRepository {
  freezeDealFields(input: FreezeDealFieldsInput): Promise<FreezeDealFieldsOutput>;
}

export type { FreezeDealFieldsInput, FreezeDealFieldsOutput } from "../dto/freeze-field.dto";
