/**
 * ExecuteCreateSupervisorySubscription - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateSupervisorySubscription Use Case
 *
 * DDD: Application use case for create Subscription.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateSupervisorySubscriptionInput, CreateSupervisorySubscriptionOutput } from "../dto/subscription.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { SubscriptionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateSupervisorySubscription {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly subscription: SubscriptionRepository
  ) {}

  async execute(input: CreateSupervisorySubscriptionInput): Promise<CreateSupervisorySubscriptionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.supervisionId();

    // All field names extracted from OpenAPI spec: active, regulatorParticipantId, scope
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.scope) {
      throw new ValidationError("scope is required");
    }
    if (!input.regulatorParticipantId) {
      throw new ValidationError("regulatorParticipantId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (supervision domain)
    const entityId = this.idGenerator.supervisionId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.subscription.createSupervisorySubscription({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateSupervisorySubscriptionOutput;
  }
}
