/**
 * ExecuteListSettlementInstructions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSettlementInstructions Use Case
 *
 * DDD: Application use case for list Instruction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSettlementInstructionsInput, ListSettlementInstructionsOutput } from "../dto/instruction.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { InstructionRepository } from "../ports";

export class ExecuteListSettlementInstructions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly instruction: InstructionRepository
  ) {}

  async execute(input: ListSettlementInstructionsInput): Promise<ListSettlementInstructionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.settlementsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.instruction.listSettlementInstructions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSettlementInstructionsOutput;
  }
}
