/**
 * ExecuteGetSettlementInstruction - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSettlementInstruction Use Case
 *
 * DDD: Application use case for get Instruction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSettlementInstructionInput, GetSettlementInstructionOutput } from "../dto/instruction.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { InstructionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSettlementInstruction {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly instruction: InstructionRepository
  ) {}

  async execute(input: GetSettlementInstructionInput): Promise<GetSettlementInstructionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.settlementsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).instructionId) {
      throw new ValidationError("instructionId is required");
    }
    const instructionId = (input as any).instructionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.instruction.getSettlementInstruction({ instructionId: instructionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${instructionId}`);
    }

    return entity as GetSettlementInstructionOutput;
  }
}
