/**
 * Participant Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ParticipantEntity } from "@settora/core/participants/models/index.js";
import { participantsSchemas } from "@settora/core/participants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "participants";

export function createParticipant(overrides: Partial<ParticipantEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    assuranceLevel: overrides.assuranceLevel ?? faker.lorem.word(),
    legalName: overrides.legalName ?? faker.lorem.word(),
    participantId: overrides.participantId ?? `ptc_${ulid().toLowerCase()}`,
    role: overrides.role ?? "brokerDealer",
    status: overrides.status ?? "active",
    ...overrides,
  };

  return participantsSchemas.Participant.parse(raw);
}

export function participantBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createParticipant(overrides));
}
