/**
 * CancelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CancelRepository Port
 *
 * DDD: Application port for cancelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CancelSettlementInstructionInput, CancelSettlementInstructionOutput } from "../dto/cancel.dto";
export interface CancelRepository {
  cancelSettlementInstruction(input: CancelSettlementInstructionInput): Promise<CancelSettlementInstructionOutput>;
}

export type { CancelSettlementInstructionInput, CancelSettlementInstructionOutput } from "../dto/cancel.dto";
