/**
 * SendRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SendRepository Port
 *
 * DDD: Application port for sendrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SendSettlementInstructionInput, SendSettlementInstructionOutput } from "../dto/send.dto";
export interface SendRepository {
  sendSettlementInstruction(input: SendSettlementInstructionInput): Promise<SendSettlementInstructionOutput>;
}

export type { SendSettlementInstructionInput, SendSettlementInstructionOutput } from "../dto/send.dto";
