/**
 * Repository interface for AgreedState
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AgreedStateEntity
} from "../models/agreed-state.entity.js";
/**
 * AgreedStateRepository Interface
 */
export interface AgreedStateRepository extends ReadRepository<AgreedStateEntity, string, Record<string, never>> {

}
