/**
 * Routes for FreezeField
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { freezeDealFields } from "../handlers/freeze-field.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function freezeFieldRoutes(fastify: FastifyInstance) {
  // POST /v1/deals/{dealId}/freeze-fields (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/deals/:dealId/freeze-fields",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dealId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDealsDependenciesForRequest();
        await freezeDealFields(request, reply, deps);
      });
    }
  );


}
