/**
 * Routes for Provenance
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAssetProvenance } from "../handlers/provenance.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function provenanceRoutes(fastify: FastifyInstance) {
  // GET /v1/provenance/{assetId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/provenance/:assetId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { assetId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDealsDependenciesForRequest();
        await getAssetProvenance(request, reply, deps);
      });
    }
  );


}
