/**
 * RulebookRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RulebookRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RulebookRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RulebookRepository,
} from "@settora/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RulebookRepositoryDdb } from "./rulebook-repository.ddb.js";

/**
 * RulebookRepositoryAdapter
 *
 * Implements RulebookRepository port for infrastructure layer.
 */
export class RulebookRepositoryAdapter implements RulebookRepository {
  private readonly ddb: RulebookRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RulebookRepositoryDdb(this.dynamoClient);
  }

  async listRulebookVersions(input: Parameters<RulebookRepository['listRulebookVersions']>[0]): Promise<Awaited<ReturnType<RulebookRepository['listRulebookVersions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRulebookVersions(input);
  }

  async getRulebookVersion(input: Parameters<RulebookRepository['getRulebookVersion']>[0]): Promise<Awaited<ReturnType<RulebookRepository['getRulebookVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRulebookVersion(input);
  }
}
