/**
 * VoteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VoteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VoteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VoteRepository,
} from "@settora/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VoteRepositoryDdb } from "./vote-repository.ddb.js";

/**
 * VoteRepositoryAdapter
 *
 * Implements VoteRepository port for infrastructure layer.
 */
export class VoteRepositoryAdapter implements VoteRepository {
  private readonly ddb: VoteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VoteRepositoryDdb(this.dynamoClient);
  }

  async listGovernanceVotes(input: Parameters<VoteRepository['listGovernanceVotes']>[0]): Promise<Awaited<ReturnType<VoteRepository['listGovernanceVotes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGovernanceVotes(input);
  }

  async castGovernanceVote(input: Parameters<VoteRepository['castGovernanceVote']>[0]): Promise<Awaited<ReturnType<VoteRepository['castGovernanceVote']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.castGovernanceVote(input);
  }
}
