/**
 * Participant Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/participants.openapi.types.js";
import { schemas } from "../schemas/participants.schemas.js";

/**
 * Entity: ParticipantEntity
 * Description: Represents the Participant domain model.
 * Source: schemas.Participant
 * Type: Domain Entity (API)
 */
export const ParticipantEntitySchema = schemas.Participant;
export type ParticipantEntity = components["schemas"]["Participant"];
