/**
 * Subscription DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Subscription DTOs
 *
 * DDD: Application DTOs for Subscription use cases.
 */

import type { CreateSupervisorySubscriptionRequestInput, GetSupervisorySubscriptionParams, ListSupervisorySubscriptionsParams } from "@settora/core/supervision/types";

export type ListSupervisorySubscriptionsInput = ListSupervisorySubscriptionsParams;

export type CreateSupervisorySubscriptionInput = CreateSupervisorySubscriptionRequestInput;

export type GetSupervisorySubscriptionInput = GetSupervisorySubscriptionParams;

export type ListSupervisorySubscriptionsOutput = {};

export type CreateSupervisorySubscriptionOutput = {};

export type GetSupervisorySubscriptionOutput = {};
