/**
 * ExecuteListCorporateActionEvents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCorporateActionEvents Use Case
 *
 * DDD: Application use case for list CorporateAction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCorporateActionEventsInput, ListCorporateActionEventsOutput } from "../dto/corporate-action.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { CorporateActionRepository } from "../ports";

export class ExecuteListCorporateActionEvents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly corporateAction: CorporateActionRepository
  ) {}

  async execute(input: ListCorporateActionEventsInput): Promise<ListCorporateActionEventsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dealsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.corporateAction.listCorporateActionEvents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCorporateActionEventsOutput;
  }
}
