/**
 * ExecuteRecordCorporateActionEvent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordCorporateActionEvent Use Case
 *
 * DDD: Application use case for get CorporateAction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordCorporateActionEventInput, RecordCorporateActionEventOutput } from "../dto/corporate-action.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { CorporateActionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordCorporateActionEvent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly corporateAction: CorporateActionRepository
  ) {}

  async execute(input: RecordCorporateActionEventInput): Promise<RecordCorporateActionEventOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dealsId();

    // All field names extracted from OpenAPI spec: attestedBy, details, eventType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dealId) {
      throw new ValidationError("dealId is required");
    }
    const dealId = (input as any).dealId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.corporateAction.recordCorporateActionEvent({ dealId: dealId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${dealId}`);
    }

    return entity as RecordCorporateActionEventOutput;
  }
}
