/**
 * ExecuteCreateTradeDeal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateTradeDeal Use Case
 *
 * DDD: Application use case for create Deal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateTradeDealInput, CreateTradeDealOutput } from "../dto/deal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { DealRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateTradeDeal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deal: DealRepository
  ) {}

  async execute(input: CreateTradeDealInput): Promise<CreateTradeDealOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dealsId();

    // All field names extracted from OpenAPI spec: dealType, externalRef, participantIds
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.dealType) {
      throw new ValidationError("dealType is required");
    }
    if (!input.participantIds) {
      throw new ValidationError("participantIds is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (deals domain)
    const entityId = this.idGenerator.dealsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.deal.createTradeDeal({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateTradeDealOutput;
  }
}
