/**
 * ExecuteGetAssetProvenance - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAssetProvenance Use Case
 *
 * DDD: Application use case for get Provenance.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAssetProvenanceInput, GetAssetProvenanceOutput } from "../dto/provenance.dto";
import type { ExecutionContextService, IdGeneratorService } from "@settora/services/_shared/index.js";
import type { ProvenanceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAssetProvenance {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly provenance: ProvenanceRepository
  ) {}

  async execute(input: GetAssetProvenanceInput): Promise<GetAssetProvenanceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dealsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assetId) {
      throw new ValidationError("assetId is required");
    }
    const assetId = (input as any).assetId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.provenance.getAssetProvenance({ assetId: assetId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assetId}`);
    }

    return entity as GetAssetProvenanceOutput;
  }
}
